### PR TITLE
Highlight 'self' in Python

### PR DESCRIPTION
**Pull request by jonesnc**
Highlight the `self` parameter with `#6baa81`. This would be helpful to me.

Thanks for this theme, I think it's great!

### CODE REVIEW

**Comment by mdx97** [comment]
Hi Nathan, thanks for the PR. I don't really use this theme anymore. I'd be willing to discuss a maintainership swap with you if you wanted. Just let me know!

**Comment by jonesnc** [comment]
Yeah I'd be willing to take over maintenance of the repo. Would I have permissions to push updates to the VS Code Extensions Marketplace as well?

Thanks again.

**Comment by jonesnc** [comment]
Any updates on this?

**Comment by jonesnc** [comment]
If transferring ownership is going to be an issue, I don't mind forking this repo and creating my own theme. If I do that, I'll be sure to credit this theme as inspiration. Either way works for me.

**Comment by mdx97** [comment]
You can go ahead and do that if you wish! Right now I don't really have the time to go about transferring the VSCode marketplace account over, so if that works for you go ahead.

**Comment by jonesnc** [comment]
Sounds good! I'll go ahead and close this issue.

**Pull request closed without merging**
